"""nullable false.

Revision ID: 14bc563e2aff
Revises: 77259e4c1ed5
Create Date: 2020-05-10 05:03:42.869422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14bc563e2aff'
down_revision = '77259e4c1ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manga', 'author',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('manga', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('review', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('review', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('review', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('manga', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('manga', 'author',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
